config/routes.rb
require 'api_contraints'
Rails.application.routes.draw do
 

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? && (request.env['warden'].user.has_role? :admin)
  end
  
  get 'dashboard/index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :omniauth_callbacks
  resources :services
  resources :things
  resources :dashboard
  resources :speech
  resources :messages, only: [:new, :create]
  resources :charges

  match '/dashboard/search/:query' => 'dashboard#search', :as => 'search', via: [:get, :post]
  match "/auth/:provider/callback" => "omniauth_callbacks#create", via: [:get, :post]

  resources :locations do 
    resources :zones do 
      post 'sort', on: :collection
    end
  end
  constraints resque_constraint do
   mount Resque::Server, :at => "/resque"
  end

  resources :admin, only: [:index]

  namespace :admin do
        resources :faqs
        resources :messages
        resources :users
  end 
  
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
     resources :users, :only => [:show]
    end
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'pages#show', id: 'home', as: :unauthenticated_root
    end
  end
  
end

app/models/thing.rb
class Thing < ActiveRecord::Base
	belongs_to :user
    belongs_to :zone
    has_many :events
    acts_as_list :scope => :zone

    before_destroy :remove_firebase
    
    def switch_value 
    end
    def lock_value
    end
    def dimmer_value
    end
    
    
    # Gather events from firebase by device

    def firebase_events
    
        client = Firebase::Client.new(ENV["FIREBASE_URL"])
        
        if self.device_type == "temperatureMeasurement"
            temps = client.get("events/"+self.uid+"/temperature")
            return temps.body
        elsif self.device_type == "switch"
            switches = client.get("events/"+self.uid+"/switch")
            return switches.body
        elsif self.device_type == "dimmer"
            dimmers = client.get("events/"+self.uid+"/dimmder")
            return dimmers.body
        elsif self.device_type == "relativeHumidityMeasurement"
            hums = client.get("events/"+self.uid+"/humidity")
            return hums.body
        elsif self.device_type == "motion"
            mots = client.get("events/"+self.uid+"/motion")
            return mots.body
        elsif self.device_type == "illuminant"
            illums = client.get("events/"+self.uid+"/illuminant")
            return illums.body
        elsif self.device_type == "contact"
            conts = client.get("events/"+self.uid+"/contact")
            return conts.body
        elsif self.device_type == "battery"
            bats = client.get("events/"+self.uid+"/battery")
            return bats.body
        elsif self.device_type == "lock"
            locks = client.get("events/"+self.uid+"/lock")
            return locks.body
        elsif self.device_type == "power"
            pows = client.get("events/"+self.uid+"/power")
            return pows.body
        elsif self.device_type == "energy"
            engs = client.get("events/"+self.uid+"/enrgy")
            return engs.body
        elsif self.device_type == "presence"
            pres = client.get("events/"+self.uid+"/presence")
            return pres.body

        end 
            
    end

    
    # Import events into local mysql from firebase 
    
    def import_events
        unless self.firebase_events == nil
            self.firebase_events.to_hash.each do |x|
                event = Event.find_or_initialize_by(name: x[0])
                event.update(name: x[0])
                event.update(date: x[1]["date"])
                event.update(value: x[1]["value"])
                event.update(thing_id: self.id)
                event.save!
            end
     
        end 

    end 


    # Delete device specific events from firebase 

    def remove_firebase
        client = Firebase::Client.new(ENV["FIREBASE_URL"])
        
        if self.device_type == "temperatureMeasurement"
            client.delete("events/"+self.uid+"/temperature")
        elsif self.device_type == "switch"
            client.delete("events/"+self.uid+"/switch")
        elsif self.device_type == "dimmer"
            client.delete("events/"+self.uid+"/dimmder")
        elsif self.device_type == "relativeHumidityMeasurement"
            client.delete("events/"+self.uid+"/humidity")
        elsif self.device_type == "motion"
            client.delete("events/"+self.uid+"/motion")
        elsif self.device_type == "illuminant"
            client.delete("events/"+self.uid+"/illuminant")
        elsif self.device_type == "contact"
            client.delete("events/"+self.uid+"/contact")
        elsif self.device_type == "battery"
            client.delete("events/"+self.uid+"/battery")
        elsif self.device_type == "lock"
            client.delete("events/"+self.uid+"/lock")
        elsif self.device_type == "power"
            client.delete("events/"+self.uid+"/power")
        elsif self.device_type == "energy"
            client.delete("events/"+self.uid+"/energy")
        elsif self.device_type == "presence"
            client.delete("events/"+self.uid+"/presence")
        end 
    end
    
    # Remove a device from firebase completely (Used when user deletes a device or their account)

    def remove_firebase_item
        client = Firebase::Client.new(ENV["FIREBASE_URL"])
        client.delete("events/"+self.uid)
    end 
    


    # Methods for collecting device information from SmartThings

    def switch_details
        @user ||= User.find(user_id)
        @user.smartthings.show_switch(self.uid)
    end

    def contact_details
        @user ||= User.find(user_id)
        @user.smartthings.show_contact(self.uid)
    end

    def power_details
        @user ||= User.find(user_id)
        @user.smartthings.show_power(self.uid)
    end

    def energy_details
        @user ||= User.find(user_id)
        @user.smartthings.show_energy(self.uid)
    end

    def presence_details
        @user ||= User.find(user_id)
        @user.smartthings.show_presence(self.uid)
    end

    def dimmer_details
        @user ||= User.find(user_id)
        @user.smartthings.show_dimmer(self.uid)
    end


     def motion_details
        @user ||= User.find(user_id)
        @user.smartthings.show_motion(self.uid)
    end
    def motion_events
        @user ||= User.find(user_id)
        @user.smartthings.motion_events(self.uid)
    end
    def lock_details
        @user ||= User.find(user_id)
        @user.smartthings.show_lock(self.uid)
    end 
    def illuminant_details
        @user ||= User.find(user_id)
        @user.smartthings.show_illuminant(self.uid)
    end 

    def battery_details
        @user ||= User.find(user_id)
        @user.smartthings.show_battery(self.uid)
    end 
    def temperature_details
        @user ||= User.find(user_id)
        @user.smartthings.show_temperature(self.uid)
    end
    def humidity_details
        @user ||= User.find(user_id)
        @user.smartthings.show_humidity(self.uid)
    end
    def  lock_details
        @user ||= User.find(user_id)
        @user.smartthings.show_lock(self.uid)
    end
      
    
    # Enqueue a value retrieval from ST and send it to firebase. Useful for devices that do not update very often or when a user intially logs in. 
    # You can find the workers in /thinglayer/app/workers

    def device_value        
           if self.device_type == "dimmer"
                Resque.enqueue(GetDimmer, self.id)
                return nil
            elsif self.device_type == "temperatureMeasurement" 
                Resque.enqueue(GetTemperature, self.id)
                return nil 
            elsif self.device_type == "relativeHumidityMeasurement" 
                Resque.enqueue(GetHumidity, self.id)
                return nil
            elsif self.device_type == "motion" 
                Resque.enqueue(GetMotion, self.id)
                return nil
            elsif self.device_type == "contact" 
                Resque.enqueue(GetContact, self.id)
                return nil
            elsif self.device_type == "lock" 
                Resque.enqueue(GetLock, self.id)
                return nil
            elsif self.device_type == "battery" 
                Resque.enqueue(GetBattery, self.id)
                return nil
            elsif self.device_type == "switch" 
                Resque.enqueue(GetSwitch, self.id)
                return nil
            elsif self.device_type == "illuminant" 
                Resque.enqueue(GetIlluminant, self.id)
                return nil
            elsif self.device_type == "power" 
                Resque.enqueue(GetPower, self.id)
                return nil
            elsif self.device_type == "energy" 
                Resque.enqueue(GetEnergy, self.id)
                return nil
            elsif self.device_type == "presence" 
                Resque.enqueue(GetPresence, self.id)
                return nil
            end
    end
    

    # Format the display output for a device type 
    
    def display_type
        if self.device_type == "relativeHumidityMeasurement" 
            return "Humidity"
        elsif self.device_type == "temperatureMeasurement"
            return "Temperature"
        elsif self.device_type == "contact"
            return "Contact"
        elsif self.device_type == "illuminant"
            return "Illuminance"
        elsif self.device_type == "battery"
            return "Battery"
        elsif self.device_type == "lock"
            return "Lock"
        elsif self.device_type == "switch"
            return "Switch"
        elsif self.device_type == "dimmer"
            return "Dimmer"
        elsif self.device_type == "motion"
            return "Motion"
        end
            
    end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
	before_filter :authenticate_user!
	def index
		@user = User.find(current_user)
		@things = @user.things 

		smartthings = @user.services.where(:provider => "smartthings")
		if params[:import] == "true" 
			if smartthings != nil 
				@user.smartthings.import
			end
		end 
		
	end 

	def show
		@user = User.find(current_user)
		@thing = @user.things.find(params[:id])
	end

    def edit
    	@user = User.find(current_user)
		@thing = @user.things.find(params[:id])
    end

	def update
		@user = User.find(current_user)
		@thing = @user.things.find(params[:id])

			if params[:thing][:source]
				if params[:thing][:source] == "remote"
					if @user.services.smartthings
						if @thing.device_type == "switch" 
							if params[:thing][:switch_value] != ""
			    				@user.smartthings.switch_value(@thing.uid, params[:thing][:switch_value])
			    			end
		    			elsif @thing.device_type == "dimmer"
		    			    if params[:thing][:dimmer_value] != ""
			        			@user.smartthings.dimmer_level(@thing.uid, params[:thing][:dimmer_value])
			        		end
		    			elsif @thing.device_type == "lock"
	    			   		if params[:thing][:lock_value] != ""
	    						@user.smartthings.lock_value(@thing.uid, params[:thing][:lock_value])
	    					end
					    end
					end
				end
			
				else 
        		respond_to do |format|
		      	if @thing.update(thing_params)
			        format.html { redirect_to things_path, notice: 'Thing was successfully updated.' }
			        format.json { render :show, status: :created, location: @thing }
			   
		      	else
			        format.html { render :new }
			        format.json { render json: @thing, status: :unprocessable_entity }
      			end
	     	end 
	    end   
	end
	def destroy
		@user = User.find(current_user)
      	@thing = @user.things.find(params[:id])
	    @thing.destroy
	    respond_to do |format|
	      format.html { redirect_to things_path, notice: 'Thing was successfully destroyed.' }
	      format.json { head :no_content }
    end
  end


	private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @user = User.find(current_user)
      @thing = @user.things.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :label, :description, :visible, :zone_id, :switch_value, :switch_type, :dimmer_value, :position, :indoor)
    end
end

app/views/things/_form.html.erb
<%= form_for([@thing], :class=> "panel form-horizontal form-bordered" ) do |f| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <span class="panel-title">Edit Thing</span>
          </div>
          <div class="panel-body no-padding-hr">
            <% if @thing.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

                  <ul>
                  <% @thing.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
              <% end %>
              </ul>
            </div>
           <% end %>
            <div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
              <div class="row">
                <label class="col-sm-4 control-label">Name</label>
                <div class="col-sm-8">
                 <%= f.text_field :name, :class=> "form-control" %>
                </div>
              </div>
            </div>
            <div class="form-group no-margin-hr no-margin-b panel-padding-h">
              <div class="row">
                <label class="col-sm-4 control-label">Description</label>
                <div class="col-sm-8">
                  <%= f.text_area :description, :class=> "form-control" %>
                </div>
              </div>
            </div>
            <div class="form-group no-margin-hr no-margin-b panel-padding-h">
              <div class="row">
                <label class="col-sm-4 control-label">Zone</label>
                <div class="col-sm-8">
                  <%= f.collection_select :zone_id , @user.zones.all, :id, :name, {:include_blank => 'Select One'}, {:class => 'form-control'}  %>
                  
                </div>
              </div>
            </div>
            <div class="form-group no-margin-hr no-margin-b panel-padding-h">
              <div class="row">
                <label class="col-sm-4 control-label">Visible on Dashboard</label>
                <div class="col-sm-8">
                  <%= f.check_box :visible, :class=> "form-control" %>
                </div>
              </div>
            </div>
            <div class="form-group no-margin-hr no-margin-b panel-padding-h">
              <div class="row">
                <label class="col-sm-4 control-label">Device Indoors</label>
                <div class="col-sm-8">
                  <%= f.check_box :indoor, :class=> "form-control" %>
                </div>
              </div>
            </div>
          </div>
          <div class="panel-footer text-right">
            <%= link_to 'Cancel', things_path, :class=> "btn btn-danger" %>
            <%= f.submit :class=> "btn btn-primary" %>
          </div>
        </form>
      </div>
<% end %>

app/views/things/edit.html.erb
<h2><%= @thing.label %> - <smaller><%= @thing.device_type %></smaller></h2>
<%= render 'form' %>

app/views/things/index.html.erb
  <% content_for :page_header do %>
    Listing Things
  <% end %>
  <% content_for :page_actions do %>
    <%= link_to dashboard_index_path, :class => 'btn btn-primary btn-labeled', :style=>"width: 100%;" do %>
                <span class="btn-label icon fa fa-chevron-left"></span>Back
    <% end %>
  <% end %>
  <% content_for :page_search do %>
  <form action="" class="pull-right col-xs-12 col-sm-6">
              <div class="input-group no-margin">
                <span class="input-group-addon" style="border:none;background: #fff;background: rgba(0,0,0,.05);"><i class="fa fa-search"></i></span>
                <input type="search" id="search" placeholder="Search..." class="form-control no-padding-hr" style="border:none;background: #fff;background: rgba(0,0,0,.05);">
              </div>
            </form>
  <% end %>


<!-- 11. $JQUERY_DATA_TABLES ===========================================================================

				jQuery Data Tables
-->

				<div class="panel panel-default">
					<div class="panel-heading">
						Device Management
					</div>
		
					<div class="panel-body">
						<div class="table-primary">
							<table class="table table-striped table-bordered table-hover" id="table">
								<thead>
									<tr>
										<th>Name</th>
										<th>Device</th>
										<th>Zone</th>
										<th>Type</th>
										<th></th>
										

									</tr>
								</thead>
								<tbody>
									<% @things.each do |thing| %>
								    
									<tr class="gradeX">
										<td><%= thing.name %></td>
										<td><%=link_to thing.label, thing_path(thing) %></td>
										<% if thing.zone %>
										<td><%= thing.zone.name %></td>
										<% else %>
										<td></td>
										<% end %>
										<td><%= thing.device_type %></td>

										<td class="text-center">
										
										 <%= link_to thing_path(thing) do %>
				                          <span class="btn btn-default icon fa fa-eye"></span>
				                        <% end %>
				                        <%= link_to edit_thing_path(thing) do %>
				                          <span class="btn btn-default icon fa fa-pencil"></span>
				                        <% end %>
				                        <%= link_to  thing_path(thing), method: :delete, data: { confirm: 'Are you sure?' }, :class=> "hidden-sm hidden-xs" do %>
				                          <span class="btn btn-danger icon fa fa-trash-o"></span>
				                        <% end %>
										</td>
										
									</tr>
								
								<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
<!-- /11. $JQUERY_DATA_TABLES -->



				<!-- Javascript -->
				<script>
					oTable = $('#table').dataTable({
					   "pagingType": "full_numbers",
					   "stateSave": true,
					   "dom": 'T<"clear">lfrtip',
					   "sDom": '<"H"lr>t<"F"ip>',
					   "aoColumnDefs" : [ {
					            'bSortable' : false,
					            'aTargets' : ["no-sort"]
					        } ]
					        
					});

					  $("#search").keyup(function() {
					   oTable.fnFilter(this.value);
					  });
				</script>
				<!-- / Javascript -->

app/views/things/show.html.erb
  <% content_for :page_header do %>
    <%= @thing.label %>
  <% end %>
  <% content_for :page_actions do %>
   

  <% end %>
  <% content_for :page_search do %>
        <form action="" class="pull-right col-xs-12 col-sm-6">
          <div class="input-group no-margin">
            <span class="input-group-addon" style="border:none;background: #fff;background: rgba(0,0,0,.05);"><i class="fa fa-search"></i></span>
            <input type="search" id="search" placeholder="Search..." class="form-control no-padding-hr" style="border:none;background: #fff;background: rgba(0,0,0,.05);">
          </div>
        </form>

  <% end %>

    
    
    
    <div class="panel panel-default">
      <div class="panel-heading">
        Chart
      </div>
      <div class="panel-body">
        <%= render 'things/charts/chart' %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        Details
      </div>
      <div class="panel-body">
        <div class="table-primary">
          <table class="table table-striped table-bordered table-hover" id="table">
              <thead>
                  <tr>
                      <th>Event ID</th>
                      <th>Date</th>
                      <th>Value</th>
                      <th></th>
                      

                  </tr>
              </thead>
              <tbody>
                  <% @thing.events.each do |event| %>
                  
                  <tr class="gradeX">
                      <td><%= event.name %></td>
                      <td><%= event.date.to_datetime %></td>
                      <td><%= event.value %></td>
                      <td class="text-center"></td>
                      
                      
                  </tr>
              
              <% end %>
              </tbody>
          </table>
      </div>
    </div>
    </div>
<!-- /11. $JQUERY_DATA_TABLES -->



                <!-- Javascript -->
                <script>
                    oTable = $('#table').dataTable({
                       "stateSave": true,
                       "dom": 'T<"clear">lfrtip',
                       "pagingType": "full_numbers",
                       "sDom": '<"H"lr>t<"F"ip>',
                       "aoColumnDefs" : [ {
                                'bSortable' : false,
                                'aTargets' : ["no-sort"]
                            } ]
                            
                    });
                    var rswfPath = "<%= asset_url('copy_csv_xls_pdf.swf') %>"
                    var tt = new $.fn.dataTable.TableTools( oTable, {
                        "sRowSelect": "os",
                        "sSwfPath": rswfPath
                    });

                    $( tt.fnContainer() ).insertAfter('div.dataTables_length');

                    $("#search").keyup(function() {
                        oTable.fnFilter(this.value);
                    });
                </script>