config/routes.rb
require 'api_contraints'
Rails.application.routes.draw do
 

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? && (request.env['warden'].user.has_role? :admin)
  end
  
  get 'dashboard/index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :omniauth_callbacks
  resources :services
  resources :things
  resources :dashboard
  resources :speech
  resources :messages, only: [:new, :create]
  resources :charges

  match '/dashboard/search/:query' => 'dashboard#search', :as => 'search', via: [:get, :post]
  match "/auth/:provider/callback" => "omniauth_callbacks#create", via: [:get, :post]

  resources :locations do 
    resources :zones do 
      post 'sort', on: :collection
    end
  end
  constraints resque_constraint do
   mount Resque::Server, :at => "/resque"
  end

  resources :admin, only: [:index]

  namespace :admin do
        resources :faqs
        resources :messages
        resources :users
  end 
  
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
     resources :users, :only => [:show]
    end
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'pages#show', id: 'home', as: :unauthenticated_root
    end
  end
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  authorize_actions_for ApplicationAuthorizer
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @messages = Message.all
    respond_with([:admin, @message])
  end

  def show
    respond_with([:admin, @message])
  end

  def new
    @message = Message.new
    respond_with([:admin, @message])
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    flash[:notice] = 'Message was successfully created.' if @message.save
   respond_with([:admin, @message])
  end

  def update
    flash[:notice] = 'Message was successfully updated.' if @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with([:admin, @message])
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:user_id, :subject, :body)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html



  def new
    @message = Message.new
    respond_with(@message)
  end


  def create
    @message = Message.new(message_params)
    flash[:notice] = 'Message was successfully created.' if @message.save
    redirect_to(page_path('help'))
  end


  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:user_id, :subject, :body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/admin/messages/_form.html.erb
<%= form_for([:admin, @message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', ([:admin, @message]) %> |
<%= link_to 'Back', admin_messages_path %>

app/views/admin/messages/index.html.erb
<h1>Listing messages</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td>
            <% if @message.user? %>
              <%= message.user.email %>
            <% end %>

        </td>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', ([:admin, message]) %></td>
        <td><%= link_to 'Edit', edit_admin_message_path([:admin, @message]) %></td>
        <td><%= link_to 'Destroy', ([:admin, message]) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/admin/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_messages_path %>

app/views/admin/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_admin_message_path(@message) %> |
<%= link_to 'Back', admin_messages_path %>