config/routes.rb
require 'api_contraints'
Rails.application.routes.draw do
 

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? && (request.env['warden'].user.has_role? :admin)
  end
  
  get 'dashboard/index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :omniauth_callbacks
  resources :services
  resources :things
  resources :dashboard
  resources :speech
  resources :messages, only: [:new, :create]
  resources :charges

  match '/dashboard/search/:query' => 'dashboard#search', :as => 'search', via: [:get, :post]
  match "/auth/:provider/callback" => "omniauth_callbacks#create", via: [:get, :post]

  resources :locations do 
    resources :zones do 
      post 'sort', on: :collection
    end
  end
  constraints resque_constraint do
   mount Resque::Server, :at => "/resque"
  end

  resources :admin, only: [:index]

  namespace :admin do
        resources :faqs
        resources :messages
        resources :users
  end 
  
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
     resources :users, :only => [:show]
    end
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'pages#show', id: 'home', as: :unauthenticated_root
    end
  end
  
end

app/views/shared/_header.html.erb
		<div>
			<div class="row">
				<!-- Page header, center on small screens -->
				<div class="col-md-2 page-actions">
					<%= yield :page_actions %>
				</div>
				<div class="col-md-3">
					<h1>
						<%= yield :page_header %>
					</h1>
				</div>

				
				
				

			   

			
				
				 <!-- Search field -->
				<div class="col-md-7 search-box">
					<%= yield :page_search %>
				</div>
			</div>
		</div>

app/views/shared/_menu.html.erb
<!-- 4. $MAIN_MENU =================================================================================

		Main menu

		Notes:
		* to make the menu item active, add a class 'active' to the <li>
		  example: <li class="active">...</li>
		* multilevel submenu example:
			<li class="mm-dropdown">
			  <a href="#"><span class="mm-text">Submenu item text 1</span></a>
			  <ul>
				<li>...</li>
				<li class="mm-dropdown">
				  <a href="#"><span class="mm-text">Submenu item text 2</span></a>
				  <ul>
					<li>...</li>
					...
				  </ul>
				</li>
				...
			  </ul>
			</li>
-->
	<div id="main-menu" role="navigation" class="hidden-print">
		<div id="main-menu-inner">
			<ul class="navigation">
				<li>
					<%= link_to  dashboard_index_path do%>
					<i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span>
					<% end %>
				</li>
				<li class="mm-dropdown">
					<a tabindex="-1" href="#"><i class="menu-icon fa fa-home"></i><span class="mm-text">Locations</span></a>
					<ul>
						<% current_user.locations.each do |location| %>
						<li class="mm-dropdown">
							<a tabindex="-1" href="<%= location_path(location) %>"><span class="mm-text"><%= location.name %></span></a>
							<ul>
								<% location.zones.each do |zone| %>
								<li>
									<%= link_to location_zone_path(zone.location, zone) do %>
										<span class="mm-text"><%= zone.name %></span></a>
									<% end %>
								</li>
								<% end %>
								<li>
									<%= link_to new_location_zone_path(location) do %>
										<span class="mm-text">Add Zone</span>
									<% end %>
								</li>
								<li>
									<%= link_to location_zones_path(location) do %>
										<span class="mm-text">Manage Zones</span>
									<% end %>
								</li>
							</ul>
						</li>
						<% end %>
						<li>
							<%= link_to new_location_path do %>
								<span class="mm-text">Add Location</span>
							<% end %>
						</li>
						<li>
							<%= link_to locations_path do %>
								<span class="mm-text">Manage Locations</span>
							<% end %>
						</li>
					</ul>
				</li>
				<li>
					<%= link_to  speech_index_path do%>
					<i class="menu-icon fa fa-microphone"></i><span class="mm-text">Voice Command</span>
					<% end %>
				</li>
				<li>
					<%= link_to  things_path do%>
					<i class="menu-icon fa fa-cloud"></i><span class="mm-text">Things</span>
					<% end %>
				</li>
				<% if user_signed_in? %>
					<% if current_user.has_role? :admin %>
						<li class="mm-dropdown">
							<a tabindex="-1" href="#"><i class="menu-icon fa fa-home"></i><span class="mm-text">Admin</span></a>
							<ul>
								<li>
								<%= link_to admin_messages_path do %>
									<span class="mm-text">Messages</span>
								<% end %>
								</li>
								<li>
									<%= link_to admin_users_path do %>
									<span class="mm-text">Users</span>
									<% end %>
								</li>
								<li>
									<%= link_to admin_faqs_path do %>
									<span class="mm-text">Faqs</span>
									<% end %>
								</li>
							</ul>
						</li>
					<% end %>
				<% end %>
			</ul>
		</ul> <!-- / .navigation -->
	</div> <!-- / #main-menu-inner -->
</div> <!-- / #main-menu -->
<!-- /4. $MAIN_MENU -->

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
       </button>
	  <%= link_to unauthenticated_root_path, :class=>"navbar-brand"  do %>
	  	ThingLayer
	  <% end %>
    </div>


    
      <ul class="nav navbar-top-links navbar-right">
	  <% if user_signed_in? %>
		<!-- Right Nav -->
           <li class="dropdown">
			<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
				<i class="dropdown-icon fa fa-user"></i>
				<span><%= current_user.username %></span>
			</a>
			<ul class="dropdown-menu">
				<li>
					<%= link_to edit_user_registration_path(current_user)  do %>
						<i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings
					<% end %>
				</li>
				<li>
					<%= link_to destroy_user_session_path, :method => :delete  do%>
						<i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out
					<% end %>
				</li>
			</ul>
		</li>
		<% else %>
			<li><%= link_to "Sign Up", new_user_registration_path %> </li>
			<li><%= link_to "Sign In", new_user_session_path %> </li>

		<% end %>
      </ul>
      

    <% if user_signed_in? %>
    	<%= render "shared/sidebar" %>
    <% end %>
  
</nav>

app/views/shared/_sidebar.html.erb
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <%= link_to dashboard_index_path do %>
                                <i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            <% end %>
                        </li>

                        <li>    
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Locations<span class="fa arrow"></span></a>
                           
                            <ul class="nav nav-second-level">
                                <% current_user.locations.each do |location| %>
                                    <li>

                                        <a href="#"><%= location.name %> <span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                 <%= link_to location_path(location) do %>
                                                        <span>Location Overview</span>
                                                    <% end %>
                                            </li>
                                            <% location.zones.each do |zone| %>
                                                <li>
                                                    <%= link_to location_zone_path(zone.location, zone) do %>
                                                        <span><%= zone.name %></span>
                                                    <% end %>
                                                </li>
                                            <% end %>
                                          
                                            <li>
                                                <%= link_to new_location_zone_path(location) do %>
                                                    <span>Add Zone</span>
                                                <% end %>
                                            </li>
                                            <li>
                                                <%= link_to location_zones_path(location) do %>
                                                    <span>Manage Zones</span>
                                                <% end %>
                                            </li>
                                        </ul>
                                        <!-- /.nav-third-level -->
                                    </li>
                             
                                 <% end %>
                                 <li>
                                    <%= link_to new_location_path do %>
                                        <span>Add Location</span>
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to locations_path do %>
                                        <span>Manage Locations</span>
                                    <% end %>
                                </li>
                            </ul>
                           
                           
                                    
                                       
                        
                         
                            <!-- /.nav-second-level -->
                           
                            
                            <li> 
                               <%= link_to "Manage Things", things_path %>
                            </li>
                            <li>
                               <%= link_to "Services", services_path %>
                            </li>
                            <li>
                               <%= link_to "Help", page_path('help') %>
                            </li>
                        

                        
                   
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->