config/routes.rb
require 'api_contraints'
Rails.application.routes.draw do
 

  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? && (request.env['warden'].user.has_role? :admin)
  end
  
  get 'dashboard/index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :omniauth_callbacks
  resources :services
  resources :things
  resources :dashboard
  resources :speech
  resources :messages, only: [:new, :create]
  resources :charges

  match '/dashboard/search/:query' => 'dashboard#search', :as => 'search', via: [:get, :post]
  match "/auth/:provider/callback" => "omniauth_callbacks#create", via: [:get, :post]

  resources :locations do 
    resources :zones do 
      post 'sort', on: :collection
    end
  end
  constraints resque_constraint do
   mount Resque::Server, :at => "/resque"
  end

  resources :admin, only: [:index]

  namespace :admin do
        resources :faqs
        resources :messages
        resources :users
  end 
  
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
     resources :users, :only => [:show]
    end
  end

  get "/pages/*id" => 'pages#show', as: :page, format: false

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'pages#show', id: 'home', as: :unauthenticated_root
    end
  end
  
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	belongs_to :location
	has_many :things, -> { order("position ASC") }


	# Zone averages 


	def average_temp
		things = self.things.where(:device_type => 'temperatureMeasurement')
		temps = 0

		things.each do |thing|
			temp = thing.events.where("STR_TO_DATE(date,'%m/%d%Y')" == Date.today).average(:value)
			unless temp == nil 
				temps = temp + temps
			end
		end 
		return temps
	end 


end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @location = Location.find(params[:location_id])
    @zones = @location.zones.all 
    
  end

  # GET /zones/1
  # GET /zones/1.json
  def show

    @user = User.find(@zone.location.user)
    #@st_dimmers = @user.smartthings.dimmers.index_by {|device| device["id"]}
    
    @things = @zone.things.where(:visible => true).order(:position)
  end

  # GET /zones/new
  def new
    @location = Location.find(params[:location_id])
    @zone = @location.zones.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
   @location = Location.find(params[:location_id])
   @zone = @location.zones.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to [@location, @zone], notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to [@location, @zone], notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
    params[:thing].each_with_index do |id, index|
     Thing.where(id: id).update_all({position: index+1})
    end
    render nothing: true
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to location_zones_path(@location), notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @location = Location.find(params[:location_id])
      @zone = @location.zones.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name, :ancestry, :description)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for([@location, @zone], :class=> "form-horizontal form-bordered" ) do |f| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              Zone Form
            </div>
            <div class="panel-body no-padding-hr">
              <% if @zone.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

                    <ul>
                    <% @zone.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                <% end %>
                </ul>
              </div>
             <% end %>
              <div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
                <div class="row">
                  <label class="col-sm-4 control-label">Name</label>
                  <div class="col-sm-8">
                   <%= f.text_field :name, :class=> "form-control" %>
                  </div>
                </div>
              </div>
              <div class="form-group no-margin-hr no-margin-b panel-padding-h">
                <div class="row">
                  <label class="col-sm-4 control-label">Description</label>
                  <div class="col-sm-8">
                    <%= f.text_area :description, :class=> "form-control" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="panel-footer text-right">
              <%= link_to 'Cancel', location_zones_path(@location), :class=> "btn btn-danger" %>
              <%= f.submit :class=> "btn btn-primary" %>
            </div>

        </form>
      </div>
<% end %>

app/views/zones/create.html.erb
<h1>Zones#create</h1>
<p>Find me in app/views/zones/create.html.erb</p>

app/views/zones/destroy.html.erb
<h1>Zones#destroy</h1>
<p>Find me in app/views/zones/destroy.html.erb</p>

app/views/zones/edit.html.erb
  <% content_for :page_header do %>
    Editing <%= @zone.name %>
  <% end %>
  <% content_for :page_actions do %>
    <%= link_to location_zones_path(@location), :class => 'btn btn-primary btn-labeled', :style=>"width: 100%;" do %>
                <span class="btn-label icon fa fa-chevron-left"></span>Back
    <% end %>
  <% end %>
  <% content_for :page_search do %>

  <% end %>


<%= render 'form' %>

app/views/zones/index.html.erb
  <% content_for :page_header do %>
    Listing Zones
  <% end %>
  <% content_for :page_actions do %>
    <%= link_to dashboard_index_url, :class => 'btn btn-primary btn-labeled', :style=>"width: 100%;" do %>
                <span class="btn-label icon fa fa-chevron-left"></span>Back
    <% end %>
  <% end %>
  <% content_for :page_search do %>
  <form action="" class="pull-right col-xs-12 col-sm-6">
              <div class="input-group no-margin">
                <span class="input-group-addon" style="border:none;background: #fff;background: rgba(0,0,0,.05);"><i class="fa fa-search"></i></span>
                <input type="search" id="search" placeholder="Search..." class="form-control no-padding-hr" style="border:none;background: #fff;background: rgba(0,0,0,.05);">
              </div>
            </form>
  <% end %>


<div class="panel">
  <div class="panel-body">

    <table class="table table-striped table-bordered table-hover" id="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @zones.each do |zone| %>
          <tr>
            <td><%= zone.name %></td>
            <td><%= zone.description %></td>
            <td class="text-center">
              <%= link_to location_zone_path(@location, zone) do %>
                <span class="btn btn-default icon fa fa-eye"></span>
              <% end %>
              <%= link_to  edit_location_zone_path(@location, zone) do %>
                <span class="btn btn-default icon fa fa-pencil"></span>
              <% end %>
              <%= link_to  location_zone_path(@location, zone), method: :delete, data: { confirm: 'Are you sure?' } , :class=> "hidden-sm hidden-xs" do %>
                <span class="btn btn-danger icon fa fa-trash-o"></span>
              <% end %>
            </td>
           
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Zone', new_location_zone_path(@location) %>



    <!-- Javascript -->
        <script>
          oTable = $('#table').dataTable({
             "pagingType": "full_numbers",
             "stateSave": true,
             "dom": 'T<"clear">lfrtip',
             "sDom": '<"H"lr>t<"F"ip>',
             "aoColumnDefs" : [ {
                      'bSortable' : false,
                      'aTargets' : ["no-sort"]
                  } ]
                  
          });

            $("#search").keyup(function() {
             oTable.fnFilter(this.value);
            });
        </script>
        <!-- / Javascript -->

app/views/zones/new.html.erb
  <% content_for :page_header do %>
    New Zone
  <% end %>
  <% content_for :page_actions do %>
    <%= link_to location_zones_path(@location), :class => 'btn btn-primary btn-labeled', :style=>"width: 100%;" do %>
                <span class="btn-label icon fa fa-chevron-left"></span>Back
    <% end %>
  <% end %>
  <% content_for :page_search do %>

  <% end %>

<%= render 'form' %>

app/views/zones/show.html.erb
  <% content_for :page_header do %>
    <%= @zone.name %>
  <% end %>
  
  <% content_for :page_actions do %>
   
  <% end %>

  <% content_for :page_search do %>

  <% end %>



<% @switch_state_changed = false %>
<% @dimmer_state_changed = false %>
<script src="https://cdn.firebase.com/js/client/1.1.3/firebase.js"></script>
           

    <div class="row grid" data-update-url='<%= sort_location_zones_url(@location) %>'>
    
     <% @things.each do |thing| %>
                      <% if thing.zone_id != nil %>
                        <% if thing.device_type == "dimmer" %>
                          <%= render partial: "tiles/dimmer", locals: {dimmer: thing}%>
                        <% elsif thing.device_type == "switch" %>
                          <%= render partial: "tiles/switch", locals: {switch: thing}%>
                        <% elsif thing.device_type == "lock" %>
                          <%= render partial: "tiles/lock", locals: {lock: thing}%>
                        <% elsif thing.device_type == "temperatureMeasurement" %>
                          <%= render partial: "tiles/temperature", locals: {temp: thing}%>
                        <% elsif thing.device_type == "relativeHumidityMeasurement" %>
                          <%= render partial: "tiles/humidity", locals: {humidity: thing}%>
                        <% elsif thing.device_type == "motion" %>
                          <%= render partial: "tiles/motion", locals: {motion: thing}%>
                        <% elsif thing.device_type == "contact" %>
                          <%= render partial: "tiles/contact", locals: {contact: thing}%>
                        <% elsif thing.device_type == "battery" %>
                          <%= render partial: "tiles/battery", locals: {battery: thing}%>
                        <% elsif thing.device_type == "illuminant" %>
                          <%= render partial: "tiles/illuminant", locals: {illuminant: thing}%>
                        <% elsif thing.device_type == "power" %>
                          <%= render partial: "tiles/power", locals: {power: thing}%>
                        <% elsif thing.device_type == "energy" %>
                          <%= render partial: "tiles/energy", locals: {energy: thing}%>
                        <% elsif thing.device_type == "presence" %>
                          <%= render partial: "tiles/presence", locals: {presence: thing}%>
                        <% end %>
                      <% end %>
                    <% end %>  
    </div>



<script>
$(function () {
    $(".grid").sortable({
        tolerance: 'pointer',
        revert: 'invalid',
        placeholder: 'col-md-2 col-sm-4 col-xs-6 placeholder tile',
        helper: 'clone',
        appendTo: 'body',
        handle: ".handle",
        forceHelperSize: true,
        
        start: function(event, ui) {
            $('.row-fluid > div.tile:visible:first').addClass('real-first-child');
        }, 
        stop: function(event, ui) {
            $('.row-fluid > div.real-first-child').removeClass('real-first-child');
        },
        change: function(event, ui) {
            $('.row-fluid > div.real-first-child').removeClass('real-first-child');
            $('.row-fluid > div.tile:visible:first').addClass('real-first-child');
        },
        update: function( event, ui ) {
           var sorted = $(".grid").sortable( "serialize");
           console.log(sorted)
           $.post($(this).data('update-url'), sorted)
        }
    });
});



   
</script>

<script>
    $('.toggle').on('click',function() {

          var form = $(this).parents('form:first');

         
          form.submit();
         
              
    });
</script>


<% @zone.things.each do |thing| %>
<script>
 
   <% if thing.device_type == "switch" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/switch");
    <% elsif thing.device_type == "dimmer" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/level");
    <% elsif thing.device_type == "temperatureMeasurement" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/temperature");
    <% elsif thing.device_type == "relativeHumidityMeasurement" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/humidity");
    <% elsif thing.device_type == "motion" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/motion");
    <% elsif thing.device_type == "contact" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/contact");
    <% elsif thing.device_type == "illuminant" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/illuminance");
    <% elsif thing.device_type == "battery" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/battery");
    <% elsif thing.device_type == "lock" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/lock");
    <% elsif thing.device_type == "power" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/power");
    <% elsif thing.device_type == "energy" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/energy");
    <% elsif thing.device_type == "presence" %>
    var myFirebaseRef_<%=thing.id%> = new Firebase("<%= ENV["FIREBASE_URL"] %>/events/<%= thing.uid %>/presence");
    <% end %>



    var query_<%=thing.id %> = myFirebaseRef_<%=thing.id %>.endAt().limit(1);
    query_<%=thing.id %>.on('child_added', function(snapshot) {
        var value = snapshot.val()
            if (value.name == "switch"){
                     $('.switch_'+value.device).bootstrapToggle(value.value)
                     console.log("changed switch value")
                     
            
                
            }

            if (value.name == "level"){
                var levelValue = $('.dimmer_'+value.device).slider("value")
                if (value.value != levelValue){
                     $('.dimmer_'+value.device).slider("value", value.value)
                }
               
               
            }
            if (value.name == "motion"){
              $('.motion_'+value.device).html(value.value);

                if(value.value == "active"){
                  $('.motion_'+value.device).html("<button type='button' class='btn btn-warning btn-circle btn-xl disabled'><i class='fa fa-angle-double-right '></i></button>");
                }else{
                   $('.motion_'+value.device).html("<button type='button' class='btn btn-success btn-circle btn-xl disabled'><i class='fa fa-pause '></i></button>");
                }
              

            }
            if (value.name == "contact"){
            
              if(value.value == "open"){
                  $('#contact_'+value.device).html("<button type='button' class='btn btn-warning btn-circle btn-xl disabled'><i class='fa fa-times'></i></button>");
                 
                }else{
                  $('#contact_'+value.device).html("<button type='button' class='btn btn-success btn-circle btn-xl disabled'><i class='fa fa-check'></i></button>");
                }

            }
            if (value.name == "lock"){
                if(value.value == "locked"){
                  $('.lock_'+value.device).bootstrapToggle("on")
                     console.log("changed lock value")
                }else{
                   $('.lock_'+value.device).bootstrapToggle("off")
                     console.log("changed lock value")
                }
                       
            }
          

            if (value.name == "illuminance"){
                if(value.unit == undefined){
                   var display_unit = "Lux"
                  
                }else{
                 var display_unit = value.unit 
                }
              $('.illuminant_'+value.device).html(value.value+" "+display_unit);

            }

             if (value.name == "battery"){
              if(value.unit == undefined){
                   var display_unit = "%"
                  
                }else{
                 var display_unit = value.unit 
                }
              $('.battery_'+value.device).html(value.value+" "+display_unit);

            }

            if (value.name == "energy"){
              $('.energy_'+value.device).html(value.value+ " %");

            }

            if (value.name == "presence"){
                if (value.value == "present"){
                  $('.presence_'+value.device).html("<button type='button' class='btn btn-success btn-circle btn-xl disabled'><i class='fa fa-user'></i></button>");
                }else{
                  $('.presence_'+value.device).html("<button type='button' class='btn btn-warning btn-circle btn-xl disabled'><i class='fa fa-user-times'></i></button>");
                }
              
            }

            if (value.name == "power"){
              
                if(value.unit == undefined){
                   var display_unit = "watts"
                  
                }else{
                 var display_unit = value.unit 
                }

                $('.power_'+value.device).html(value.value+ " "+display_unit);

            }
            if (value.name == "temperature"){
              if(value.unit == undefined){
                   var display_unit = "F"
                  
                }else{
                 var display_unit = value.unit 
                }
                $('.temperature_'+value.device).html("<button type='button' class='btn btn-success btn-circle btn-xl disabled temp-button'>"+value.value+"</br>"+display_unit+"</button>");
              

            }

            if (value.name == "humidity"){
              if(value.unit == undefined){
                   var display_unit = "%"
                  
                }else{
                 var display_unit = value.unit 
                }
              $('.humidity_'+value.device).html(value.value+" "+display_unit);

            }
           
        console.log(value.device+' '+value.value+' '+value.unit);
        
    });
</script>
<% end %>


<script>
    $('.switch_class').click(function() {

          var form = $(this).parents('form:first');

         
          form.submit();
         
              
    });
</script>


<script>

<% @things.where(:device_type => "dimmer").each do |dimmer| %>


var colorful_sliders_options = {
    'range': 'min',
    'min': 1,
    'max': 99,
    'value': 0,
        'stop': function(event, ui) {
            var value = $(".dimmer_<%= dimmer.uid %>").slider("value");
            $(".dimmer_value_<%= dimmer.uid %>").val(value);
            var form = $(this).parents('form:first');
           
            form.submit();
          
            

        }
};
$('.dimmer_<%= dimmer.uid %>').slider(colorful_sliders_options);




<% end %>
</script>


   

app/views/zones/update.html.erb
<h1>Zones#update</h1>
<p>Find me in app/views/zones/update.html.erb</p>